import { msg } from '@lit/localize';

export const CLONE_NAMES: Record<string, () => string> = {
  John: () => msg('John'),
  Jack: () => msg('Jack'),
  Tom: () => msg('Tom'),
  Jim: () => msg('Jim'),
  Bill: () => msg('Bill'),
  Steven: () => msg('Steven'),
  Ivan: () => msg('Ivan'),
  Vasily: () => msg('Vasily'),
  Dmitry: () => msg('Dmitry'),
  Alexey: () => msg('Alexey'),
  Sergey: () => msg('Sergey'),
  Petar: () => msg('Petar'),
  Miloš: () => msg('Miloš'),
  Nenad: () => msg('Nenad'),
  Nemanja: () => msg('Nemanja'),
  Miodrag: () => msg('Miodrag'),
  Nikola: () => msg('Nikola'),
};

export const DISTRICT_NAMES: Record<string, () => string> = {
  Barajevo: () => msg('Barajevo'),
  Čukarica: () => msg('Čukarica'),
  Grocka: () => msg('Grocka'),
  Lazarevac: () => msg('Lazarevac'),
  Mladenovac: () => msg('Mladenovac'),
  'Novi Beograd': () => msg('Novi Beograd'),
  Obrenovac: () => msg('Obrenovac'),
  Palilula: () => msg('Palilula'),
  Rakovica: () => msg('Rakovica'),
  'Savski Venac': () => msg('Savski Venac'),
  Sopot: () => msg('Sopot'),
  'Stari Grad': () => msg('Stari Grad'),
  Surčin: () => msg('Surčin'),
  Voždovac: () => msg('Voždovac'),
  Vračar: () => msg('Vračar'),
  Zemun: () => msg('Zemun'),
  Zvezdara: () => msg('Zvezdara'),
};
