export const VALIDATOR_TYPES = {
  ValidatorFacade: Symbol('ValidatorFacade'),
  ProgramValidator: Symbol('ProgramValidator'),
  ProgramValidatorFacade: Symbol('ProgrmaValidatorFacade'),
  NameValidator: Symbol('NameValidator'),
  NameValidatorFacade: Symbol('NameValidatorFacade'),
  ThemeValidator: Symbol('ThemeValidator'),
  ThemeValidatorFacade: Symbol('ThemeValidatorFacade'),
  CloneTemplateValidator: Symbol('CloneTemplateValidator'),
  CloneTemplateValidatorFacade: Symbol('CloneTemplateValidatorFacade'),
  SidejobValidator: Symbol('SidejobValidator'),
  SidejobValidatorFacade: Symbol('SidejobValidatorFacade'),
  DistrictTypeValidator: Symbol('DistrictTypeValidator'),
  DistrictTypeValidatorFacade: Symbol('DistrictTypeValidatorFacade'),
  FactionValidator: Symbol('FactionValidator'),
  FactionValidatorFacade: Symbol('FactionValidatorFacade'),
  ConstantsValidator: Symbol('ConstantsValidator'),
  ConstantsValidatorFacade: Symbol('ConstantsValidatorFacade'),
};
